### PR TITLE
Mayhem Integration

### PR DESCRIPTION
**Pull request by srithon**
Mayhem hero submission

### CODE REVIEW

**Comment by noahShinabarger** [comment]
@srithon Phase II of the Heroes program closed at the end of December. We're currently working on rules for Phase III, and I would encourage you to resubmit this at that time--it would probably qualify. Thanks!

**Comment by srithon** [comment]
> @srithon Phase II of the Heroes program closed at the end of December. We're currently working on rules for Phase III, and I would encourage you to resubmit this at that time--it would probably qualify. Thanks!

Oh, that's weird. I got an email from Alex Brewer on January 27 that told me to make this PR, since I initially submitted it in mid December. Since I submitted it during Phase II, this still counts for Phase II, right?

( @noahShinabarger incase it doesn't notify you otherwise )

**Comment by noahShinabarger** [comment]
Got it--I just couldn't see any commits that were made in December on your repo, which is why I was confused. We can go ahead and count this for Phase II, but the tests-per-second is below 10, and needs to be above 10 before it can be accepted, so try to get your test running faster (eliminate any unecessary setup or looping, etc.) and tag me if you get it working.

**Comment by srithon** [comment]
Hey @noahShinabarger, I brought up the runs per second to 16.

**Pull request merged**
